### ISSUE TITLE
Nexus support

### ISSUE THREAD

**Issue by jbadeau** [yarnpkg/rfcs#10]
Do you plan to add support for maven/nexus? Would be really nice to be able to install use nexus as a backing for private artifacts.

I am aware that nexus can proxy and host npm modules. I am talking about hosting standard maven based artifacts e.g. jars, wars, zips, tars ..

Is the API stable enough to build nexus support on?

**Comment by thejameskyle** [comment]
Can you explain in more detail what this would mean? I've never used Maven or Nexus and don't know what the ask is here

**Comment by Daniel15** [comment]
It sounds like the ask is for Yarn to support things that aren't Node.js packages, such as `.jar` and .war` files you get when you build Java apps? Is that right @jbadeau?

James, I think this fits in really well with your tweets about being language-agnostic (https://twitter.com/thejameskyle/status/787883837111963649) 😄 

>  I've never used Maven or Nexus and don't know what the ask is here

@thejameskyle - Nexus is an artifact repository. Imagine something like an internal npm server you host on your own server, except it can also host Python (PyPI), Ruby (gems), Java (Maven) packages. Companies use it to host internal packages - We use it internally at Facebook for our Java libraries.

Maven is an "all-in-one" build and dependency management system for Java. In "JavaScript speak", imagine npm, Gulp and Webpack all rolled into a single tool.

**Comment by Daniel15** [comment]
https://github.com/yarnpkg/yarn/issues/547 covers using separate npm repositories (so it would cover loading npm packages from a Nexus server), we haven't really talked about supporting non-npm packages though.

**Comment by thejameskyle** [comment]
> I think this fits in really well with your tweets about being language-agnostic 

Yeah, I'd very much like to do that, there's a lot of work to be done to prepare for it though.

Is this really being language-agnostic though? It sounds like you still want to use JS just with a different type of registry, which is something else entirely.

**Comment by Daniel15** [comment]
> Is this really being language-agnostic though?

I'll let @jbadeau clarify, but they did mention:

> standard maven based artifacts e.g. jars, wars, zips, tars ..

JARs and WARs are the result of compiling Java applications (you feed the compiler a bunch of `.java` files and it spits out a single `.jar` or `.war` for your library or app), so it sounds like they want to do something with Yarn and Java libraries.

**Comment by jbadeau** [comment]
Hello:

Nexus is a very popular artifact repository used by many companies to manage many types of artifacts not just java although java is the most popular.

What I am asking is:

- would it be possible that yarn can download artifacts of types jar and tar.gz to be used by java applications

For me this is not really about being 'language agnostic' but about being 'repository/registry agnostic'. I have seen in the yarn source that there is api like:

https://github.com/yarnpkg/yarn/tree/master/src/registries
https://github.com/yarnpkg/yarn/tree/master/src/resolvers/exotics

I don't see why nexus couldn't  be added as YAR (YET ANOTHER REGISTRY)

In the future I could image that yarn could even publish npm packages to nexus

**Comment by jbadeau** [comment]
I am even open to implement but I wanted to know if that is something you guys were thinking about and if the idea sounds feasible.

**Comment by thejameskyle** [comment]
> would it be possible that yarn can download artifacts of types jar and tar.gz (archives containing js e.g. webjars) to be used by java applications

Well packages can contain anything at all so you could pretty easily publish and install packages with jar's inside of them. Nothing needs to be added for that.

> For me this is not really about being 'language agnostic' but about being 'repository/registry agnostic'. I have seen in the yarn source that there is api like:

However right now I don't think this makes sense. We can't just add resolvers and support every registry out there, registries are structured in many different ways with different sets of configuration files needed for each one.

What would be the benefit of that if you can already publish packages containing jar's to the npm registry?

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
