### ISSUE TITLE
Shipping Yarn with Node?

### ISSUE THREAD

**Issue by ZakariaRidouh** [yarnpkg/rfcs#12]
It would be a great convenience if node can bundle yarn with it just like it does to npm. It shouldn't add a significant download size to node and would potentially help Yarn grow significantly.

cheers!
:sparkles:

**Comment by joshmanders** [comment]
I started a discussion on this a while ago https://github.com/nodejs/node/issues/9161

**Comment by thejameskyle** [comment]
This isn't a request that Yarn can fulfill on it's own. Node is the one that would have to approve bundling it, we can talk to them about it and make sure we're meeting any requirements, but ultimately they are the ones who would have to okay it.

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
