### ISSUE TITLE
Install from a git repositories subfolder

### ISSUE THREAD

**Issue by vinnymac** [yarnpkg/rfcs#15]
### Summary

Installing via a subfolder in a specific repository appears to be a very [popular request for NPM](https://github.com/npm/npm/issues/2974). In the end it did not align with the [NPM philosophy](https://github.com/npm/npm/issues/2974#issuecomment-169451651). I am not sure I need this myself. Yet many people have wanted this over the last 4 years making me wonder whether it would be worth adding to yarn. It is at least worth discussing.

### Major Points
- Monolithic repositories such as babel would be able to publish a single package, instead of many. This allows for a more flexible method of installation.
- Python's pip installer does this already
  `git+https://git.repo/some_repo.git@egg=subdir&subdirectory=subdir_path`

### Proposed Formats
- `git://x.com/path/to/whatever#some-branch some/sub/dir`
- `git://user@example.com/path/to/resource/[path/to/directory]#commit-ref`
- `git://x.com/path/to/whatever#some-branch:/some/directory`
- `git://x.com/path/to/whatever#some-branch::/some/directory`

### Thoughts
- Does it align with yarn's philosophy given many organizations use monolithic repositories?
- Would it be desired or expected for this to work on the yarn registry as well as git?
- Does it have any demand or was this only specific to NPM?
- Do other package managers support this feature other than pip?

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
