### ISSUE TITLE
Support downloading packages from arbitrary URLs

### ISSUE THREAD

**Issue by graingert** [yarnpkg/rfcs#17]
**Do you want to request a *feature* or report a *bug*?**
Request feature

**What is the current behavior?**
You can't cownload arbitrary js files and store them appropriately.

**What is the expected behavior?**
I'd like to be able to take a URL like "https://example.com/path/to/random/jsfile.js" and put the content into `node_modules/some-module-name/index.js`

I currently use a tiny little bower.json to download just those external packages:

```json
{
  "name": "abc",
  "version": "1.0.0",
  "description": "xyz",
  "dependencies": {
    "some-module-name":"https://example.com/path/to/random/jsfile.js"
  }
}
```

**Please mention your node.js, yarn and operating system version.**

Moved from https://github.com/yarnpkg/yarn/issues/1646

**Comment by ljharb** [comment]
Typically the way to do this is to make a gist and put that URL in package.json.

As-is, your suggestion would break `npm install`, since I don't think npm can download single JS files like that.

**Comment by graingert** [comment]
@ljharb but I want to get a specific file from the web and update it every time I do "yarn install" (taking into account cache headers and etags etc)

**Comment by ljharb** [comment]
Then that step should be in a postinstall script in some deep in your graph, instead of directly as a dependency.

**Comment by graingert** [comment]
>  in some deep in your graph

?

**Comment by graingert** [comment]
> Then that step should be in a postinstall script

it currently is. But I'd rather it be managed by yarn than bower.

**Comment by ljharb** [comment]
I'd suggest using curl over bower for it.

If yarn were to natively handle a legacy pattern of downloading a file from the web (as opposed to from a proper package repository with semver support) then it'd need to do it in a separate package.json field so as not to break "dependencies" for those still using npm.

**Comment by graingert** [comment]
> then it'd need to do it in a separate package.json field so as not to break "dependencies" for those still using npm.

That's fine with me

**Comment by thejameskyle** [comment]
Yarn needs a `package.json` for the `name` and `version` fields. It can already install arbitrary `.tgz` files on the internet or a git repo. It could even install from a gist if you wanted to: https://gist.github.com/thejameskyle/78c0d4bd27705fa460de4526d623b5b8

```sh
yarn add https://gist.github.com/78c0d4bd27705fa460de4526d623b5b8.git
cat yarn.lock 
```

```yaml
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
"https://gist.github.com/78c0d4bd27705fa460de4526d623b5b8.git":
  name hello
  version "1.0.0"
  resolved "https://gist.github.com/78c0d4bd27705fa460de4526d623b5b8.git#7ed88760c0160911211aee09988691e09f32d7a5"
```

But installing a single arbitrary JS file without a `package.json` or even a git repo for version control doesn't seem like the sort of thing Yarn should add support for.

If you wanted to do this, you could add something to your build steps like:

```sh
yarn install
mkdir libs
curl https://example.com/path/to/random/jsfile.js > libs/jsfile.js
curl https://example.com/path/to/random/anotherfile.js > libs/anotherfile.js
```

However, I would encourage you to turn shared pieces of code into packages. Hopefully the bar is low enough that it shouldn't be much trouble for you. I wrote a detailed guide over here: https://yarnpkg.com/en/docs/creating-a-package

**Comment by graingert** [comment]
@thejameskyle I don't have the right to re-host the library as is

**Comment by thejameskyle** [comment]
@graingert Why is that?

**Comment by graingert** [comment]
@thejameskyle copyright, the script in question is one that the authors want you to just put into a wacky script tag:

```html
<script>
(function(w, d, s) {
  var firstScript = s.getElementsByTagName('script')[0];
  var e = document.createElement('script');
  e.src =  'https://example.com/path/to/random/jsfile.js';
  firstScript.parentNode.insertBefore(e, firstScript);
})(window, document,);
</script>
```

But I want to load it using webpack

**Comment by graingert** [comment]
I have a bunch of these, each by different authors, each with bespoke loader scripts.

**Comment by thejameskyle** [comment]
Well I'm not gonna advise any particular action regarding copyrights, licensing, or fair use. You may want to talk to a lawyer at your company or the authors of the JavaScript file you are depending on.

However, for the use case of downloading arbitrary JavaScript files from the internet as dependencies I would recommend `curl` over Yarn.

To repeat my example from before:

```sh
yarn install
mkdir libs
curl https://example.com/path/to/random/jsfile.js > libs/jsfile.js
curl https://example.com/path/to/random/anotherfile.js > libs/anotherfile.js
```

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
