### ISSUE TITLE
package changelogs

### ISSUE THREAD

**Issue by timoxley** [yarnpkg/rfcs#19]
Currently it's very difficult to know exactly what changed between different versions of packages without manually checking each package's git history, which of course most users don't have the time or patience for.

Would be good if both `yarn` & `npm` could agree on some metadata format or process for gathering and communicating changes between releases in packages, and optionally printing what would/did change before/after a successful update.

I suggest either a `history.md/.json` file or or perhaps a `"history"` key in `package.json`. If users don't opt-in to manually writing these, it could be easily retroactively autogenerated from git history on `prepublish` (or whatever it's called now). 

Another perhaps simpler alternative could be to generate these dynamically based on mapping versions to tags on github ala the https://www.npmjs.com/package/changelog package, though I think it's important for users to be able to write human-readable changelog summaries that don't necessarily map directly to commits.

I opened a similar issue on npm a few years back about this https://github.com/npm/npm/issues/5851#issuecomment-50892069 and @othiym23 seemed not against the concept.

**Comment by ljharb** [comment]
I typically see a file named "changelog.md" - i can't recall seeing "history.md" before.

Especially if npm can agree on it, having a convention in package.json for specifying changelogs seems very useful.

**Comment by timoxley** [comment]
@ljharb `History.md` is the default generated by `git-extra`'s [changelog](https://github.com/tj/git-extras/blob/master/bin/git-changelog) command, but it appears you're right, [changelog.md](https://github.com/search?utf8=%E2%9C%93&q=filename%3Achangelog.md+path%3A%2F&type=Code&ref=searchresults) is more popular than [history.md](https://github.com/search?utf8=%E2%9C%93&q=filename%3Ahistory.md+path%3A%2F&type=Code&ref=searchresults).

**Comment by thejameskyle** [comment]
Do you just want a `package.json` key, some sort of command to show the changes, or do you want to enforce that packages include a changelog?

**Comment by joshmanders** [comment]
I'd say a `package.json` key to define where changelog is at in your project directory, sorta like `main` and `version` then use that key to determine what to do.

**Comment by ljharb** [comment]
Along with a key name, it would be ideal if the file then had to conform to some kind of spec, so it could be programmatically processed.

**Comment by thejameskyle** [comment]
Okay, well if someone wants to try writing up a spec for that and submit it following [this process](https://github.com/yarnpkg/rfcs/blob/master/README.md) we can talk about it more.

**Comment by sindresorhus** [comment]
It should ideally also support [GitHub Releases](https://github.com/sindresorhus/xo/releases).

**Comment by ljharb** [comment]
@sindresorhus your github release content isn't mirrored in a github-independent file in the repo?

**Comment by sindresorhus** [comment]
@ljharb No, I don't want to clutter my repo or git history with transient changelog stuff.

**Comment by ljharb** [comment]
Hmm, it's permanently tied to the git history anyways tho, not sure how it's transient. We don't need to clutter this issue further tho, sorry.

**Comment by thejameskyle** [comment]
I don't think we should add any more features like that which are targeting specific businesses. It bothers me already that we have to treat "user/repo" as GitHub because npm did. Someone can wrap Yarn if they want that.

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
