### ISSUE TITLE
Support Hjson configs

### ISSUE THREAD

**Issue by laktak** [yarnpkg/rfcs#2]
npm uses JSON config files (package.json).

These configs are not always edited by a tool as it is often quicker/easier to just open an editor. While JSON is a simple language it is not well suited for editing (no comments, easy to add or forget a comma, etc.).

Hjson (http://hjson.org) solves these problems and makes it easy to convert to/from JSON. It can also round trip comments when the data is updated by a tool.

It would be great if yarn could support this workflow.

One option could be a `yarn edit` command that would convert package.json to Hjson and open it in the default editor, converting it back to JSON once the file is closed.

**Comment by mathieumg** [comment]
Similarly, there is http://json5.org/

**Comment by ljharb** [comment]
Published modules *must* always have a `package.json` - the flow described where it lets you edit in your preferred format sounds great, as long as it *always* produces a `package.json` file.

**Comment by thejameskyle** [comment]
We don't want to break the existing ecosystem which this would do, we'd have to add a translation step when creating the tarball

**Comment by laktak** [comment]
> We don't want to break the existing ecosystem which this would do

@thejameskyle  Actually the goal was not to break anything by pulling the config back to `package.json`. Where do you see the problem?

**Comment by mathieumg** [comment]
For instance, we currently use `package.json5` manifests but always ensure that it gets published as compliant JSON in `package.json` inside the tarball. Hopefully yarn is more open-minded in that matter than [npm is](https://github.com/npm/npm/issues/4482).

**Comment by ljharb** [comment]
fwiw, all of npm's concerns in that thread are still highly relevant and valid, so I'd even extend it to say that any alternative package.json format would *have* to be local-only - ie, never published to npm, even alongside a real package.json.

**Comment by mathieumg** [comment]
> any alternative package.json format would have to be local-only - ie, never published to npm, even alongside a real package.json.

Yep, we're thinking along the same way on that. The concern of needing comments alongside dependencies in that local-only file is an extremely valid one, as well.

**Comment by laktak** [comment]
I got a working implementation for this in the [hed](https://github.com/laktak/hed) tool (`npm install -g hed`)

> How does it work?
> 
> - `hed package.json` will convert JSON to Hjson and open it in your editor for editing
> - when you are done package.json is updated with your changes (as pure JSON)
> - any comments you added will be kept in package.meta
> - package.hjson is removed to avoid conflicting edits
> - the next time you run `hed package.json` your comments will be merged back

**Comment by doug-wade** [comment]
This doesn't seem like something yarn should support directly.  `npm` has a mess of tools that use the [`onload` script](https://docs.npmjs.com/misc/config#onload-script) to translate a differently-formatted package.json file -> package.json, which seems more reasonable than asking yarn to support every file format under the sun.  Supporting the onload script would have the added benefit of sharing translation layers between yarn and npm (for instance, the already-existing pakages for [yaml]([https://www.npmjs.com/package/package-yml), [json5](https://www.npmjs.com/package/npm-json5) and -- with a little scripting -- [hjson](https://www.npmjs.com/package/hed)).

**Comment by laktak** [comment]
@doug-wade sorry but using the onload script is really just an ugly hack.

It would be great if npm & yarn could add plugin support for this but I don't have a lot of hope for npm.

**Comment by whitecolor** [comment]
Proposal for YAML as an option https://github.com/yarnpkg/rfcs/issues/20

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
