### ISSUE TITLE
Support YAML format for manifest files (package.yaml)

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/rfcs#20]
I think it is will be very useful and convenient to fully suuport YAML format for package manifest files:

YAML

1) supports comments
2) supports multiline
3) supports external imports
4) prettier too look at and easier to read/edit

So that:
1) yarn init --yaml would create `package.yaml` (or `package.yml`) instead of json 
2) if --yaml not specified yarn would also lookup for package.yaml (yml) along with package.json
3) also include ability to convert json <--> yaml
4) while packing yarn would generate valid json for distribution

And npm wouldn't want to do this (as many other useful things)
https://github.com/npm/npm/issues/3336

I wouldn't worry about interoperability with npm because it is already broken in many other cases, and json still will remain default option.

**Comment by ljharb** [comment]
Interop with npm is critical, for the same reasons outlined in #2.

**Comment by whitecolor** [comment]
> Interop with npm is critical, for the same reasons outlined in #2.

Well then if this https://github.com/yarnpkg/rfcs/issues/21 would be implemented it would enable kind of hooks/plugin system that could be used to implement conveniences like that.

**Comment by nkt** [comment]
For npm compatibility yarn could convert `package.yaml` to `package.json` before publish package.

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
