### ISSUE TITLE
Ability to customize the local directory (instead of "node_modules")

### ISSUE THREAD

**Issue by anthony-o** [yarnpkg/rfcs#22]
As bower support was dropped, it would be good for frontend development that we could specify in some config files where do we want to put the downloaded dependencies.

Like [`directory`](https://bower.io/docs/config/) property in `.bowerrc`.

**Comment by ljharb** [comment]
This wouldn't be compatible with node's `require` algorithm, or any of the JS tooling in the ecosystem, which is the primary purpose for installing packages.

**Comment by anthony-o** [comment]
So yarn will never be addressed for front-end development use cases like bower? That's sad because for me this feature is the only blocker one so that I could use it to download my front dependencies without creating complex build architecture that would move the content of `node_modules` to some other location.

**Comment by ljharb** [comment]
node's `reqiure` algorithm is for front-end cases; since all the tooling is built around that.

**Comment by thejameskyle** [comment]
There's a decent change the directory is going to have to be customizable for supporting other languages in the future.

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
