### ISSUE TITLE
Ability to specify folder name when installing local or git

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/rfcs#23]
when do `yarn add file:./local/path` or `yarn add github:user/repo` it would be also possilbe to specify folder name where to place this module, 

because it is possible to do manually specify it in package.json
```
 "my-custom-name": "file:../local/path"
```

even if `name` prop in added package's package.json is different. This would be useful feature. But npm actually doesn't allow to do this way. If I'm correct "my-custom-name" should be the same as `name` property in installed package.json

**Comment by whitecolor** [comment]
It seems that it can be already done:

`yarn upgrade my-local-package-custom-name@file:./path/to/my/local/package`

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
