### ISSUE TITLE
Add symlink link: dependency type

### ISSUE THREAD

**Issue by mgcrea** [yarnpkg/rfcs#25]
We've been using some kind of monorepo approach for our projects for quite some time, a bit like [lerna](https://github.com/lerna/lerna) but with a more private and nested approach (our packages aren't expected to be published for now) along some specific needs: we must to link some public dependencies (eg. mongoose) that must be the exact same instance accross our subpackages (otherwise you encounter a lot of exotic bugs, edge cases), we also link our devDeps (they are shared accross all our subpackages).

At first we used [linklocal](https://github.com/timoxley/linklocal) with npm@2, leveraging a custom use of the `file:` prefix (basically just symlinking them), but npm@3 broke a lot of things related to their handling (eg. [#10343](https://github.com/npm/npm/issues/10343)). We ended up moving to [ied](https://github.com/alexanderGugel/ied) where we implemented the `file:` prefix handling using simple symlinks, that tackled our need.

I would love to be able to switch theses project to yarn but I would need a way to create this links, I can see two ways to achieve that:
- Either add a new `link:` prefix that would just create symlinks and that's it
- Add an option flag `--link-file-dependencies` that would override default `file:` handling (copying) and use symlinks instead.

--- 
Related Issue: https://github.com/yarnpkg/yarn/issues/884
Related PR: https://github.com/yarnpkg/yarn/pull/1109

**Comment by whitecolor** [comment]
I believe this would solve many current issues with local deps.

**Comment by whitecolor** [comment]
@mgcrea 
Is yarn cache going to be some how involved in the work with `link:` (will it be writing something to cache)?

**Comment by shouze** [comment]
Other dependency managers like [composer](https://getcomposer.org/) manage that kind of feature 
with repository lists:
```json
    "repositories": [
        {
            "type": "path",
            "url": "../somelib",
            "options": {
                "symlink": true
            }
        },
        {
            "type": "vcs",
            "url": "https://github.com/someuser/somelib"
        }
    ]
```
The repositories order is important of course in the resolution of the dependency.

This is a very flexible way to do library nurturing in our mono repo whilst one day make that lib released either in a public or private npm repo. This is our use case with php libs and it's very convenient.

**Comment by mgcrea** [comment]
@whitecolor yarn cache would not be involved.

@shouze,

I'm not sure how such a cascading repository resolution would work, does it mean if the local file does not exists it does a clone on GitHub? I personally would not need such feature, as I just want it to be dumb and create a symlink (even if the target does not exist yet).

**Comment by shouze** [comment]
@mgcrea yes that's it, will clone as a fallback if it exist on the remote repo.

Yes of course, making links only would be so great in a 1st time, it's also what I/we need at least.

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.

**Comment by shouze** [comment]
@kittens ok, @mgcrea ok tell me if you want to help for RFC redaction ;)

**Comment by benlangfeld** [comment]
I also need this feature; can I help with the RFC, @mgcrea?

**Comment by mgcrea** [comment]
Pull request is up: #34 🎉 .
