### ISSUE TITLE
Add --context (or --root) option

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/rfcs#26]
Well probably this could be useful if it was be possible to run yarn if it where run in another directory.

So instead of :
```
yarn && cd sub-module1 && yarn && cd ../sub-module2 && yarn && cd sub-module3 && yarn
```

to have something more flat and consistent:
```
yarn && yarn --context sub-module1 && yarn --context sub-module2 && yarn --context sub-module3
```

Or run some inquiries without changing current dir:
```
yarn why this-module --context app/app-module
```

**Comment by ljharb** [comment]
Your first example is more terse than your second - what's the advantage? Typically all commands should always be run at the project root, and when you have subprojects, that's just multiple project roots.

**Comment by whitecolor** [comment]
> Typically all commands should always be run at the project root, and when you have subprojects,

Probably you are right. I just thought if others face this issue.

**Comment by thejameskyle** [comment]
I don't see a huge advantage in doing this. But if it were to be added I'd prefer `--cwd [dir]`

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
