### ISSUE TITLE
Ability to remove particular package from cache

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/rfcs#27]
I think it would be useful to be able to remove a particular package from cache:

Something like that API:
`yarn cache remove package-name`  // will remove all found package versions
`yarn cache remove package-name@version` // remove particular version
`yarn cache remove package-name@version --type npm`

**Comment by thejameskyle** [comment]
What is `--type npm`

**Comment by whitecolor** [comment]
Names in cache `npm-async-1.5.2` I believe first is registry type, maybe another name `--registry`

**Comment by whathejoe** [comment]
+1

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
