### ISSUE TITLE
Support "extends" field

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/rfcs#29]
As a proposal. Support extending from other `json` file.
```js
{
   "extends": "../package.common.json"
}
```

So it would load "../package.common.json" and merge it with current JSON with one level deep.

**Comment by ljharb** [comment]
If this were ever published to npm, it would break all the npm clients out there.

**Comment by whitecolor** [comment]
such things will to break npm clients:
https://github.com/yarnpkg/rfcs/issues/25

**Comment by ljharb** [comment]
@whitecolor yarn itself doesn't have to be limited. but things that will leak out into the npm ecosystem (not talking about adding additional keys that won't break things, of course)? Yes, absolutely, yarn should forever be constrained to not break the npm ecosystem, full stop.

**Comment by whitecolor** [comment]
@ljharb - then I see no problem in current proposal, while packing and publishing packages.json transformed (with applied "extends") version should be pushed in the registry. Is this a problem if such approach is used?

**Comment by kittens** [comment]
@ljharb Please refrain from talking authoritatively on the project. We don't currently have intentions to break compatibility in the immediate future but we aren't committed to supporting that model long term.

**Comment by ljharb** [comment]
@kittens Indeed, I said "should" because it's my opinion, but fair enough. I'd hope there'd be lots of public discussion before breaking compatibility with the ecosystem.

@whitecolor that's a great solution that would indeed maintain compatibility.

**Comment by kittens** [comment]
@ljharb Yeah they'll be a lot of public discussion. Any significant features and changes will go through this rfcs repo. Just to clarify what "significant features" means so it doesn't seem like we'll sneak something in and label it as "minor", it definently includes breaking ecosystem changes like these.

**Comment by thejameskyle** [comment]
So back to the original proposal, a couple thoughts:

- I see more value in being able to see exactly what ends up in the final `package.json` than being able to abstract a few fields away
- How is "extends" defined, does it only apply at the top level? Is it a deep extends? If it's a deep extends how does that work in a generic way?

**Comment by whitecolor** [comment]
I believe it should be NOT deep extension as nature package.json canonical structure basically one level in depth. I think mostly it would be used for extending `scripts` and `dependencies`.

Btw if this https://github.com/yarnpkg/yarn/issues/1759 has been implemented, it would be possible to make such extensions in form of plugins. There just should be ability to inject custom logic between manifest read and processing.

**Comment by thejameskyle** [comment]
> I believe it should be NOT deep extension [...] I think mostly it would be used for extending `scripts` and `dependencies`

This seems to be contradictory, extending a nested object is doing a deep extend.

**Comment by whitecolor** [comment]
Ah yeah I mean 1 one level deep merge =)

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
