### ISSUE TITLE
Yarn outdated

### ISSUE THREAD

**Issue by MathRobin** [yarnpkg/rfcs#3]
Hi,

It's a feature request.

Yarn should support something like npm outdated. Find which packages is outdated is very useful. Mainly if you use save-exact to install a package. The way, I imagine it, is strictly the same as the npm way. Even the great excited should be to be able to choose which package you want to update like when you had too choose which resolve version you want in bower when conflicts. 

Thanks in advance

**Comment by hawkrives** [comment]
I just ran `yarn outdated` and got the normal `npm outdated` results – is that what you're looking for? (update: [found the docs](https://yarnpkg.com/en/docs/cli/outdated))

```console
$ yarn outdated
yarn outdated v0.15.1
Package                    Current      Wanted       Latest
babel-plugin-webpack-alias 1.9.0        1.9.0        2.1.1
history                    2.1.2        2.1.2        4.3.0
react-select               1.0.0-beta13 1.0.0-beta13 1.0.0-rc.2
redux-freeze               0.1.4        0.1.4        0.1.5
treo                       0.6.0-rc2    0.6.0-rc2    0.5.1
✨  Done in 3.00s.
```

**Comment by hpurmann** [comment]
I think this can be closed, right @MathRobin?

**Comment by thejameskyle** [comment]
Yeah, if you have suggestions on how it can be improved you can open another issue.

**Comment by MathRobin** [comment]
Yes it's good. Thanks
