### ISSUE TITLE
"yarn knit": a better "yarn link"

### ISSUE THREAD

**Issue by wolfgang42** [yarnpkg/rfcs#30]
> This is copied from yarnpkg/yarn#1213. @ide was the original author of that issue but I agree with the sentiment and would also like to see this feature.

<p>This is a feature request to make "yarn link" or a new command be more useful than the current behavior, which was modeled after "npm link". Before focusing on the actual linking mechanism I want to describe the desired behavior of "yarn link":</p>
<h2>Desired behavior</h2>
<p>The "yarn link" workflow should mimic publishing a package (ex: <code>dep</code>) to npm and then installing it in a dependent (ex: <code>app</code>), and keep this constraint while you're making changes to the first package. Concretely, "yarn link" should make it so that when you save a change to <code>dep</code>, the resulting state is as if you:</p>
<ol>
<li>Ran "npm publish" in <code>dep</code> (assume that it can clobber an existing version, and that you're publishing to a local registry on just your computer).</li>
<li>Ran "yarn add dep" in <code>app</code>.</li>
</ol>
<h2>Why this behavior is great</h2>
<p>This solves several problems that "yarn link" has today:</p>
<h4>Isolating <code>node_modules</code> correctly</h4>
<p>You can install <code>dep</code> in two different apps without sharing the <code>node_modules</code> of <code>dep</code>. This is a problem with Electron apps, whose V8 version is different than Node's and uses a different ABI. If you have <code>node-app</code> and <code>electron-app</code> that both depend on <code>dep</code>, the native dependencies of <code>dep</code> need to be recompiled separately for each app; <code>node-app/n_m/dep/n_m</code> must not be the same as <code>electron-app/n_m/dep/n_m</code>.</p>
<h4>Working on multiple versions</h4>
<p>You can be developing multiple different versions of <code>dep</code>. Say you have two directories, <code>dep-1</code> and <code>dep-2</code>, which have your v1 and v2 branches checked out, respectively. With "yarn link" it's not possible to make both of these directories linkable at the same time.</p>
<p>This is a problem when you are developing &amp; testing <code>dep-1</code> with <code>old-app</code> and <code>dep-2</code> with <code>new-app</code>. You don't want to be going back and forth between <code>dep-1</code> and <code>dep-2</code> running "yarn link" each time you switch which app you're testing.</p>
<h4>Faithfully representing the <code>node_modules</code> hierarchy</h4>
<p>Currently "yarn link" symlinks the entire package directory, which brings along its <code>node_modules</code> subdirectory with it. With dependency deduping and flattening, bringing in <code>dep/node_modules</code> wholesale usually produces a different <code>node_modules</code> hierarchy than running <code>yarn install</code> in <code>app</code> and installing everything from npm. This isn't a problem most of the time but it does go against Yarn's spirit of consistency and the lockfile.</p>
<h2>A practical proposal -- knitting :3</h2>
<p>This is a proposal that solves all of the problems above and isn't too hard to implement or understand. I'm going to call it "yarn knit" to distinguish it from "yarn link". Conceptually, we find all the files we'd normally publish to npm, pack them up using symlinks instead of copies of the files, publish the pack to a local registry (just a directory), and then when installing we look up packages in the local registry directory instead of npm.</p>
<h3>Running "yarn knit" inside of <code>dep</code></h3>
<p>This is the step that simulates publishing <code>dep</code>. Running "yarn knit" in <code>dep</code> finds all the files that "yarn publish" would pack up and upload to npm. Crucially, this excludes <code>node_modules</code>, and would follow the same algorithm as "yarn publish" such as reading package.json's <code>files</code> field.</p>
<p>Then it simulates publishing <code>dep</code>: it creates a directory named <code>dep-X.Y.Z</code> (where <code>X.Y.Z</code> is the version of <code>dep</code> in its package.json) inside of a global directory like <code>~/.yarn-knit</code>. A symlink is created for each file or directory that "yarn publish" would normally have packed up. This step shares some conceptual similarities with publishing to a registry, except it uses symlinks and it's local on your computer.</p>
<h3>Running "yarn knit dep" inside of <code>app</code></h3>
<p>This behaves like "yarn add dep" except that it looks at the versions of <code>dep</code> that are in the global <code>~/.yarn-knit</code> folder and takes the latest one. (You also could run "yarn link <a href="mailto:dep@X.Y.Z">dep@X.Y.Z</a>" if you wanted a more specific version, like "yarn add".)</p>
<p>"yarn knit dep" then runs most of the same installation steps that <code>yarn add dep</code> would. It creates <code>app/node_modules/dep</code> and creates symlinks for each of the symlinks under <code>~/.yarn-knit/dep-X.Y.Z</code>. Then it installs the dependencies of <code>dep</code> as usual by fetching them from npm. Finally it runs postinstall scripts.</p>
<h3>Issues</h3>
<p>One issue with this proposal is that it's not clear what to put in the lockfile after running <code>yarn link dep</code> since we don't have an npm URL for the dep yet -- it hasn't been published to npm. Another issue is that if you change package.json in <code>dep</code>, namely changing a dependency or modifying the <code>files</code> entry, you have to run <code>cd dep; yarn knit; cd app; yarn knit dep</code>.</p>

**Comment by wolfgang42** [comment]
> This is a copy of @ide's [comment](https://github.com/yarnpkg/yarn/issues/1213#issuecomment-254663542) on the original issue.

<p>(Edit: this is in response to a comment that pointed out another issue I forgot to mention. If you update the code in <code>dep</code> and bump its version, say from 1.0.0 to 1.1.0, the symlinks in <code>~/.yarn-knit/dep-1.0.0</code> will still point to the code in your working directory, which now contains 1.1.0 code.)</p>

<p>The symlinks might break but I think that's mostly OK since at that point you're done working on <code>dep</code> and have published it to npm and it's easy to go run <code>yarn add dep</code> in <code>app</code> and not use the symlinks anymore.</p>

<p>If you want to truly pin the versions of knitted packages then you'd need to have a different working directory for each version. (Git worktrees are great for this use case actually. Worktrees let you check out a repo once and then magically create semi-clones of it in separate directories, with the constraint that the worktrees need to be on different branches, which is totally OK in this scenario. The worktrees all share the same Git repo though, so if you commit in one worktree you can cherry pick that commit within another worktree.)</p>

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.

**Comment by wolfgang42** [comment]
@kittens I was following the Readme which says "You may open an issue on this repo to start a high-level discussion" without mentioning anything about the template. I will reformat the request, but perhaps that section should be reworded to make it clear that the template applies to pre-submission feedback issues as well as the actual submissions?

**Comment by robations** [comment]
As just about every issue on this repo has been closed in a similar manner, I would say this is a UI issue, unless you really wish to shut down people’s ideas.

**Comment by cpojer** [comment]
@robations we are still getting used to the rfc process. @kittens pointed out how to properly submit a proposal.
