### ISSUE TITLE
Support package.cson

### ISSUE THREAD

**Issue by danielbayley** [yarnpkg/rfcs#31]
This would play really nicely with Atom and [solve comments](https://github.com/yarnpkg/yarn/issues/1049) for free…

**Comment by thejameskyle** [comment]
lol @ljharb your down vote, such a concern troll.

@danielbayley see #2 and #20 - it is unlikely this is ever going to be added

**Comment by ljharb** [comment]
@thejameskyle i wouldn't feel it necessary if an official commitment to npm compatibility, even for a limited amount of time or "subject to reversal with notice", was given :-p

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
