### ISSUE TITLE
Prevent `yarn run` when packages are out of sync with yarn.lock

### ISSUE THREAD

**Issue by jcarbo** [yarnpkg/rfcs#32]
When running a command with `bundler`, if your installed gems are not the same as what is specified in your Gemfile.lock it will raise:
```
Could not find paranoia-2.1.0 in any of the sources
Run `bundle install` to install missing gems.
```

I think this would be a great check to add to `yarn run` to ensure you're not running commands with stale packages.

I just ran into this issue yesterday (we just switched from npm to yarn) where I updated a package on a feature branch, the branch was merged and deployed by a teammate without ever running `yarn install` which led to some issues.

**Comment by thejameskyle** [comment]
@kittens This check is fairly cheap right?

**Comment by bestander** [comment]
@thejameskyle, integrity check takes about 0.5-1 seconds because we need to init resolver and load lockfile.

**Comment by thejameskyle** [comment]
I guess the question then is that really worth the overhead, or if we cant get that time down to <200ms for it not to matter.

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
