### ISSUE TITLE
Ability to specify a parent package.json 

### ISSUE THREAD

**Issue by mnasyrov** [yarnpkg/rfcs#33]
There is NPM's feature request '[Allow to specify a parent package.json](https://github.com/npm/npm/issues/8112)' which was closed because it does not fit to NPM.

> The idea is to borrow Mavens parent.pom concept to allow specifying common dependencies, devDependencies, scripts, configs or any other property.
>
> This would be extremely helpful when using npm as a build tool for dozens of modules following the same approach, e.g. within an organization.

I think the feature really can be useful for [multi-package repositories](https://github.com/lerna/lerna) by providing more easy dependency and script management.

**Comment by thejameskyle** [comment]
In the case of multi-package repos you still wouldn't want to extend `package.json`'s, just put your devDependencies all at the top level and use them there. No need to copy them into every single `node_modules`

**Comment by kittens** [comment]
Closing this as this RFC has been issued incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit is a PR. See #16, #7, #1 for reference.
