### ISSUE TITLE
yarn.lock file extension

### ISSUE THREAD

**Issue by JuanitoFatas** [yarnpkg/rfcs#4]
https://github.com/bundler/bundler/issues/694

> The .lock extension is a long used UNIX indication that a resource is locked for changing or update by a process.

Shall we change? Maybe is too late 😭

**Comment by lacker** [comment]
Are UNIX `.lock` files really more familiar to JavaScript developers than Ruby `Gemfile.lock` files? Elixir also uses the `.lock` suffix for this sort of file: http://elixir-lang.org/getting-started/mix-otp/dependencies-and-umbrella-apps.html At some point the new usage becomes more common than the old usage, and I think we might be at that point.

**Comment by ljharb** [comment]
Technically, `yarn.lock` is indeed locked for changing or updating by the `yarn` process - humans aren't supposed to mess with it. The same is true for `Gemfile.lock`. I don't think there's any conflict here.

**Comment by JuanitoFatas** [comment]
👍

**Comment by joshmanders** [comment]
FWIW: Composer (PHP package manager) also has `composer.lock`
