### ISSUE TITLE
Show only updated packages on yarn upgrade

### ISSUE THREAD

**Issue by lukasoppermann** [yarnpkg/rfcs#47]
Hey, it would be pretty handy if yarn would by default, or with a flag, only show packages that were updated when running `yarn upgrade`. 

When debugging it can be helpful to quickly figure out if a package is actually updated to the version you expect / has been updated at all.

**Comment by bestander** [comment]
@lukasoppermann, could you start a Pull Request with the template it provides?
I think the idea is reasonable.
