### ISSUE TITLE
api.js: Yarn Public API (Programmatically use Yarn)

### ISSUE THREAD

**Issue by j** [yarnpkg/rfcs#6]
The [api.js](https://github.com/yarnpkg/yarn/blob/master/src/api.js) is currently empty.

I'm under the assumption that this is will be a way people can programmatically use yarn.

NPM has the [npm-programmatic](https://github.com/Manak/npm-programmatic) library, which is slightly a hack.

It'd be awesome to be able to use yarn programmatically for our build system.  Our current use-case is to Webpack files, get a list of the used external modules, and installing via yarn into another directory to then package and upload into AWS Lambda.

**Comment by ljharb** [comment]
I think this is an awesome idea as long as, unlike npm, the JS API follows semver too (likely better as a separate package, ofc)

**Comment by dpoindexter** [comment]
Another potential use case: Bailing early on subsequent build steps if `yarn install` is a no-op. Ordinarily this would be accomplished by a file watcher, but I also support a number of devs who don't manually recompile front-end source files as part of their ordinary workflow. For them, it's helpful for a back-end build command to also trigger a front-end recompile when needed. Checking if `yarn install` did any work is one way I can know whether a recompile is necessary after e.g. pulling changes. (Our web app's front- and back-end code currently live in a shared monorepo)

**Comment by polkovnikov-ph** [comment]
I can imagine commands that

 - scan for `require('xyz')` / `import ... from 'xyz'` and installs those packages automatically;
 - compare list of the used packages to the list of installed packages;
 - change versions of libraries with metasymbols (obviously left from other devs as legacy) into exact versions of the last installed libraries;
 - change a library with a version from github repo without looking up for a repo name in `package.json` manuallly;
 - give hints on which libs should end up in devDependencies
 - ...

They have nothing in common with the core functionality of `yarn`. These shouldn't get even into rfcs. The only thing that doesn't allow their existence is the absence of public API. Hopefully, this could be [coordinated](https://github.com/npm/npm/issues/14599) with `npm`. We don't need two competing APIs and a set of barely working converters.

**Comment by peabnuts123** [comment]
As someone who is [writing a dependency analyser](/peabnuts123/npm-dep-analyser) for NodeJS, Yarn's speed and stability make it perfect as a sub-component of my library, as I could use it to scrape what dependencies a package uses in a deterministic way. At the moment though I'm forced to run yarn from a `child_process` call and parse its output. A programmatic API would be very useful for this.

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.
