### ISSUE TITLE
 Dry run / preview mode?

### ISSUE THREAD

**Issue by glenjamin** [yarnpkg/rfcs#8]
As far as I can tell there's no way to see what yarn would do without having your node_modules folder modified.

It would be nice if there was a way to halt the install/upgrade process after the lockfile has been generated, and then either only modify the lockfile, or spit it out on stdout.

This would allow the user to diff it against their existing lockfile and decide if they're happy to proceed with downloading and installing the packages.

The two concrete times I've wanted to do this are:
1. When first downloading yarn, to see if it would process my project successfully and get an idea of what versions it would choose (workaround was to temporarily rename `node_modules`)
2. When re-installing after patching in the optional-dependencies fix, I wanted to know if it would just add in the optionals, or if it would also modify some other versions.

(Originally reported as https://github.com/yarnpkg/yarn/issues/887)

**Comment by peabnuts123** [comment]
I would also like to see this option. As the developer of a [NodeJS dependency analysing tool](/peabnuts123/npm-dep-analyser) a dry run would allow me to utilise Yarn for my dependency analysis without having to download / execute any code.

**Comment by kittens** [comment]
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.

**Comment by peabnuts123** [comment]
😢 outright closing non-radical ideas to improve your project because they aren't formatted correctly seems harsh

**Comment by bestander** [comment]
Think of this as not a dismissal of the idea but a request to resubmit as PR following the template.
