### ISSUE TITLE
Yarn shouldn't be installed from package repository

### ISSUE THREAD

**Issue by hiendv** [yarnpkg/rfcs#9]
First, I opened an issue https://github.com/yarnpkg/yarn/issues/812 for a while but it seems that you're overwhelmed and unable to process all of the issues so I think I could have your attention by bringing the issue here.

The inconsistency between the version of nodejs which yarn is running on and the version of nodejs which npm is running on brings **significant** effects.

### Why "inconsistency"?
- Yarn requires nodejs and uses `/usr/bin/nodejs` when installed from Debian package repository.
- Users may not use the same version of npm when they install a package. They may have other versions of node & npm.

### More details
- Please see [the issue](https://github.com/yarnpkg/yarn/issues/812) and [my last comment](https://github.com/yarnpkg/yarn/issues/812#issuecomment-253503861)

### Solution
_Actually I don't have a good one_
- Having a configuration of node's `execPath`
- Recommending `npm i -g yarn` rather than `apt-get/yum install yarn`

So, what's your opinion on this?

**Comment by louisgv** [comment]
I'm having the same problem when using nvm/npm to install yarn. Here's a log:

```
yarn install v0.15.1
info No lockfile found.
error TypeError: Cannot read property 'toUpperCase' of undefined
    at Array.<anonymous> (/home/lab/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/spdx-correct/index.js:82:23)
    at validTransformation (/home/lab/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/spdx-correct/index.js:173:36)
    at module.exports (/home/lab/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/spdx-correct/index.js:215:21)
    at module.exports (/home/lab/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/validate-npm-package-license/index.js:60:23)
    at isValidLicense (/home/lab/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/lib/util/normalize-manifest/util.js:16:10)
    at /home/lab/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/lib/util/normalize-manifest/fix.js:305:140
    at next (native)
    at step (/home/lab/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/lab/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by Daniel15** [comment]
> Yarn requires nodejs and uses /usr/bin/nodejs when installed from Debian package repository.

This is the standard path for Node.js on Debian. We could potentially make the `yarn` script check for either  `nodejs` **or** `node` (for people that use a non-standard installation method).

> Recommending npm i -g yarn rather than apt-get/yum install yarn

Strongly disagree. `npm` is not at all well-suited for system-level package management. Here's one of my comments from a few weeks ago:

> Advantages of using the system's native package manager rather than something like `npm install -g yarn`:
>
> - Upgrades are handled the same way as all other software on your system (`apt-get upgrade`). It's not a special snowflake.
> - All the security problems with npm (eg. packages not being signed) make it less than ideal for anything installed system wide. apt-get gives you proper GPG signature verification.
> - Using npm means you're tightly-coupled to npm. If you later want to have a better installation solution, you need to have this awkward transition period where you try to get users to switch to the newer installation method.
> - The setup instructions need the whole weird "*install Node.js first, then ensure npm is up-to-date, then install Yarn*" thing. That'd be like telling people to manually install their npm dependencies 😆 . With a proper package management system, the Yarn package would simply have a dependency on the Node.js package, and "apt-get install yarn" would install both.
> 
> If we want to appeal to people that have limited Node.js experience, we shouldn't make any assumptions that they know anything about the Node.js ecosystem or what "npm" even is.

**Comment by thejameskyle** [comment]
Agree with @Daniel15 on this, we should recommend other install options first. As for the exec path checking for both nodejs and node seems good to me

**Comment by Daniel15** [comment]
The tricky/unfortunate thing with Node.js on Debian is that "node" conflicted with another package.

See:
https://lists.debian.org/debian-devel-announce/2012/07/msg00002.html
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=614907

In the end, both packages that used the `node` binary name were renamed.

If you want to use Node installed via an alternate installation method (for example, nvm), right now I suggest symlinking `/usr/bin/nodejs` to `/usr/bin/node` so that Debian packages that use Node.js use the right version.

**Comment by Daniel15** [comment]
>  As for the exec path checking for both nodejs and node seems good to me

Filed https://github.com/yarnpkg/yarn/issues/1142 for this

**Comment by Daniel15** [comment]
Going to close this out as https://github.com/yarnpkg/yarn/issues/1142 should help

@hiendv - To resolve your current situation, I suggest `apt-get remove nodejs` and then symlink `/usr/bin/nodejs` to the version of Node you're using (probably `/usr/bin/node`).

**Comment by hiendv** [comment]
Hi, @Daniel15. First of all, thanks for your feedback. I want to share some of my opinions.

> Is there an issue with our Debian package that's causing it to use the wrong Node.js version?

No, sir. It's actually my intention in using different versions of node, for my particular tasks. I don't know how others use node but I think I'm not the only one who uses nvm.

> Strongly disagree. npm is not at all well-suited for system-level package management.
...
All the security problems with npm (eg. packages not being signed) make it less than ideal for anything installed system wide. apt-get gives you proper GPG signature verification.

Well, I'm sorry to say this but I don't think Yarn is a system-level package. For me, it's more likely to be an npm alternative. They both depend on Node. So what I was trying to say is that Yarn should be distributed like npm is - it should be coupled with a specific version of Node. I did notice about the security matters.

> The setup instructions need the whole weird "install Node.js first, then ensure npm is up-to-date, then install Yarn" thing. That'd be like telling people to manually install their npm dependencies :laughing: . With a proper package management system, the Yarn package would simply have a dependency on the Node.js package, and "apt-get install yarn" would install both.

Well, if they want to use a node package, they should have Node beforehand. For me, it doesn't look that bad :smile: But, yeah, it's more complicated than necessary.

> Using npm means you're tightly-coupled to npm. If you later want to have a better installation solution, you need to have this awkward transition period where you try to get users to switch to the newer installation method.

If there is a way to have Node comes with Yarn installed, we should get into it. But for now, despite how much I want to decouple Yarn from npm, I couldn't think of anything to link Node and Yarn properly rather than installing Yarn for each installation of Node using npm.

Considering all of the above, I understand why you recommend native package manager.

Thank you for your time and patience. I love Yarn and hope to see it's shipped with Node by default. Keep up the good work !

**Comment by Daniel15** [comment]
> Well, I'm sorry to say this but I don't think Yarn is a system-level package. For me, it's more likely to be an npm alternative. They both depend on Node.

What I mean by "system-level package" is an app you install once then use anywhere, as opposed to a project-level package where you install it only into a specific project. npm works reasonably well for project-level dependencies but falls apart for system-level ones.

> Well, if they want to use a node package, they should have Node beforehand. 

We're aiming to make Yarn completely language-agnostic. People may want to use Yarn that have never even used Node.js before. They shouldn't have to learn about Node.js and what it is just to use Yarn. 

The fact that Yarn uses Node.js is an implementation detail rather than a defining feature. It could just have easily been written in Python or Ruby or whatever else. The user experience should remain the same regardless of the language it's written in 😄

**Comment by hiendv** [comment]
@Daniel15 I know that Node.js is just an implementation. But Python, Ruby or Golang, Yarn still needs to know about the installation of Node because these packages depend on the engine.
